#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
    /config/log 
   
# copy config
if [[ ! -e /config/config.ini ]]; then
    cp /defaults/config.ini /config/config.ini
fi

# run docker as non-root
usermod -aG docker abc


# permissions
lsiown abc:abc -R \
    /config \
    /opt

