#!/usr/bin/with-contenv bash

# exec \
#     s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 5299" \
#         s6-setuidgid abc bash /opt/ibracorp/ibramenu/ibramenu.sh \
#         --datadir /config --nolaunch
